
    - name: Install Docker
      ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh




#  - name: Install Docker
#    ansible.builtin.shell: docker run --name nginx -p 80:80 -d nginx


    # - name: Install Docker Engine
    #   apt:
    #     name: docker.io
    #     state: present

    - name: Install Docker CLI
      apt:
        name: docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Create volume
      docker_volume:
        name: nginx-data
        driver: local

    - name: Run nginx Docker container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - "nginx-data:/usr/share/nginx/html:ro"        

