version: "3.9"
services:
  node:
    image: .
    ports:
      - "8080:8080"
    networks:
      - webapp
  nginx:
    image: nginx:latest
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - webapp
    depends_on:
      - node
    restart: always
networks:
  webapp:
    driver: bridge
    