version: "3.9"
services:

  nodejs:
    build: .
    ports:
      - "8080:8080"
    networks:
      - webapp
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
    networks:
      - webapp
    ports:
      - "80:80"
    depends_on:
      - nodejs

networks:
  webapp:
    driver: bridge