version: "3.3"
services:
  website1:  
    image: nginx
    ports: 
      - "8081:80"
    restart: always
    networks: 
      Net1:
        ipv4_address: 172.27.0.5
  website2: 
    image: nginx
    ports: 
      - "8082:80"
    restart: always
    networks: 
      Net1:
        ipv4_address: 172.27.0.6
networks:
  Net1:
    ipam:
      driver: default 
      config:
        - subnet: "172.27.0.0/16"
